// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
}

allprojects {
    ext {
        compileSdkVersion = 35
        minSdkVersion = 26
        targetSdkVersion = 35
        //release version
        localVersionCode = 777
        localVersionName = '7.7.7'
        //release version
        versionCode = project.findProperty("versionCode")?.toInteger() ?: localVersionCode
        versionName = project.findProperty("versionName") ?: localVersionName
    }
}