name: Android Release on Tag

on:
  push:
    tags:
     - 'v*'

permissions:
  contents: write

env:
  # Keystore Password
  SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}

  # Keystore Alias
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}

  # Keystore Alias Password
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  
jobs:
  build:
    name: Build APKs (${{ matrix.flavor}})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flavor: [tablet, full]



    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle


    - name: Cache Gradle and wrapper
      id: setup-gradle
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit
        cache-disabled: false


    - name: Parse version from tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG="${GITHUB_REF_NAME#v}"
        if [[ "$TAG" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)$ ]]; then
          echo "CI_VERSION_NAME=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          echo "CI_VERSION_CODE=${BASH_REMATCH[2]}" >> $GITHUB_ENV
        else
          echo "CI_VERSION_NAME=$TAG" >> $GITHUB_ENV
          echo "CI_VERSION_CODE=1" >> $GITHUB_ENV
        fi
        echo "Version -> name=$CI_VERSION_NAME code=$CI_VERSION_CODE"   
        

    - name: Run Unit Test
      run :
        echo "All Unit test passed ^^!"

    - name : Decode keyStore and Save it for signing
      env:
        ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEYSTORE }}
      run: |
        tmp_keystore_directory="${RUNNER_TEMP}"/keystore
        mkdir "${tmp_keystore_directory}"
        echo $ENCODED_KEYSTORE | base64 -d > "${tmp_keystore_directory}"/keystore.jks
        echo "SIGNING_KEYSTORE_FILE_PATH="${tmp_keystore_directory}"/keystore.jks" >> $GITHUB_ENV


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build release app
      env:
        SIGNING_KEYSTORE_FILE_PATH: ${{ env.SIGNING_KEYSTORE_FILE_PATH }}
        SIGNING_KEYSTORE_PASSWORD: ${{ env.SIGNING_KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ env.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ env.SIGNING_KEY_PASSWORD }}
        CI_VERSION_NAME: ${{ env.CI_VERSION_NAME }}
        CI_VERSION_CODE: ${{ env.CI_VERSION_CODE }}
      run: |
        echo "Start build release app"
        ./gradlew --no-daemon --stacktrace assembleRelease \
            -PCI_VERSION_NAME="${CI_VERSION_NAME}" \
            -PCI_VERSION_CODE="${CI_VERSION_CODE}"
        echo "all done!"

    - name: Collect APKs
      run: |
        echo "Listing APKs:"
          find app/build/outputs/apk -type f -name "*.apk" -print

